### ISSUE TITLE
通过接口 /getItems 获取的AE网络库存液滴可能不一致

### ISSUE THREAD

**Issue by Eticeweng** [koiNoCirculation/AEMobile#6]
通过AE中的`流体离散器`生成的流体液滴物品在`/getItems`接口中返回的SSE中每次`message`事件的响应都有概率不一致

这是通过该接口四次采样的AE网络中物品 **种类** 的总量
![image](https://github.com/user-attachments/assets/02f86a84-82a5-438d-90bb-cf49c0042f8f)

这是接口返回的响应数据，
可以看到前两次对应数量`3652`的响应缺少了`nbt`特征为`CgAACAAFRmx1aWQADXBsYXNtYS5veHlnZW4A`的流体液滴物品，
这种状态下的响应返回的 **流体液滴** 是只符合`"craftable":true`的，而不会展示网络中剩余的其他 **流体液滴** (`"craftable":false`)

而数量为`3740`的响应则正常返回所有的物品，包括`"craftable":true` 和 `false`的 **流体液滴**
![image](https://github.com/user-attachments/assets/f155f3f3-59a8-4abf-871f-85c13ae2fcee)

> 甚至有时会返回空的`body`
![image](https://github.com/user-attachments/assets/ca5c6478-cfd2-43fa-948b-2c9a4f3bd287)

- 已经排除网络问题导致的响应不完整，因为每次响应均能被正确解析
- 这个丢失的现象是随机发生的，貌似当网络中有正在进行的合成计划会趋向稳定发送完整的结果
- 这个现象或许和服务端的TPS有关？被监测的网络中有数种流体是被动拉取和频繁生产的，所以会在游戏的终端中闪动

**Comment by koiNoCirculation** [comment]
不稳定的原因一般是网络中的一部分被卸载掉了，需要保证整个网络载入。
液滴这部分我可能不会去处理，因为这主要就是个发任务和监视的工具，而且排查这个问题也会消耗很多精力hh

**Comment by Eticeweng** [comment]
明白了，谢谢你的回复。

我监视的整个AE网络均处在SU提供的区块加载中，应该不会出现某个设备被卸载导致无法读取。
不过液滴丢失这个问题也无伤大雅，一般多刷新几次就会重新跑出来了。
